-- Create a table for public profiles (extends auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  role text check (role in ('creator', 'company')),
  bio text,
  job_title text,
  resume_url text,
  
  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for jobs
create table public.jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  company_id uuid references public.profiles(id) not null,
  description text,
  job_type text, -- Full-time, Part-time, Contract, etc.
  rate text, -- Budget/Salary
  status text default 'active' check (status in ('active', 'closed')),
  requirements text
);

-- Set up RLS for jobs
alter table public.jobs enable row level security;

create policy "Jobs are viewable by everyone."
  on jobs for select
  using ( true );

create policy "Companies can insert jobs."
  on jobs for insert
  with check ( auth.uid() = company_id );

create policy "Companies can update their own jobs."
  on jobs for update
  using ( auth.uid() = company_id );

-- Create a table for applications
create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  job_id bigint references public.jobs(id) not null,
  creator_id uuid references public.profiles(id) not null,
  status text default 'applied' check (status in ('applied','reviewing','interview','rejected','hired')),
  note text,
  unique (job_id, creator_id)
);

alter table public.applications enable row level security;

create policy "Creators can view their applications."
  on applications for select
  using ( auth.uid() = creator_id );

create policy "Creators can apply to jobs."
  on applications for insert
  with check ( auth.uid() = creator_id );

create policy "Companies can update applications for their jobs."
  on applications for update
  using ( auth.uid() = (select company_id from public.jobs where public.jobs.id = applications.job_id) );

-- Storage buckets setup (run these in Storage section or via API if possible, otherwise manual)
-- Bucket: 'avatars' (public)
-- Bucket: 'resumes' (private/authenticated)
